'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'th' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
    th: {
        // Navbar
        'nav.home': 'หน้าแรก',
        'nav.store': 'ร้านค้า',
        'nav.wiki': 'วิกิ',
        'nav.support': 'ติดต่อสนับสนุน',
        'nav.login': 'เข้าสู่ระบบ',
        'nav.register': 'สมัครสมาชิก',
        'nav.logout': 'ออกจากระบบ',
        'nav.admin': 'แอดมิน',
        'nav.profile': 'โปรไฟล์',
        'nav.logoutConfirmTitle': 'ออกจากระบบ',
        'nav.logoutConfirmDesc': 'คุณแน่ใจหรือไม่ที่จะออกจากระบบ?',
        'nav.balance': 'ยอดเงินคงเหลือ',



        // Login
        'login.title': 'เข้าสู่ระบบ',
        'login.subtitle': 'ยินดีต้อนรับกลับมา',
        'login.email': 'อีเมล',
        'login.username': 'ชื่อผู้ใช้',
        'login.password': 'รหัสผ่าน',
        'login.rememberMe': 'จดจำฉัน',
        'login.forgotPassword': 'ลืมรหัสผ่าน?',
        'login.submit': 'เข้าสู่ระบบ',
        'login.noAccount': 'ยังไม่มีบัญชี?',
        'login.signUp': 'สมัครสมาชิก',

        // Register
        'register.title': 'สมัครสมาชิก',
        'register.subtitle': 'สร้างบัญชีของคุณ',
        'register.name': 'ชื่อผู้ใช้',
        'register.email': 'อีเมล',
        'register.password': 'รหัสผ่าน',
        'register.passwordHint': 'ต้องมีอย่างน้อย 8 ตัวอักษร',
        'register.submit': 'สมัครสมาชิก',
        'register.hasAccount': 'มีบัญชีอยู่แล้ว?',
        'register.signIn': 'เข้าสู่ระบบ',

        // Shop
        'shop.title': 'ร้านค้า',
        'shop.subtitle': 'เลือกซื้อสินค้าที่คุณต้องการ',
        'shop.search': 'ค้นหาสินค้า...',
        'shop.all': 'ทั้งหมด',
        'shop.buy': 'ซื้อสินค้า',
        'shop.price': 'ราคา',
        'shop.points': 'พอยท์',
        'shop.outOfStock': 'สินค้าหมด',
        'shop.confirmBuy': 'ยืนยันการซื้อ',
        'shop.confirmBuyDesc': 'คุณแน่ใจหรือไม่ที่จะซื้อสินค้านี้?',
        'shop.success': 'ซื้อสินค้าสำเร็จ',
        'shop.error': 'เกิดข้อผิดพลาดในการซื้อสินค้า',
        'shop.insufficientPoints': 'พอยท์ไม่พอ',
        'shop.insufficientPointsDesc': 'คุณมีพอยท์ไม่เพียงพอสำหรับซื้อสินค้านี้ กรุณาเติมเงิน',
        'shop.topup': 'เติมเงิน',
        'shop.checkOnline': 'เช็คสถานะออนไลน์',
        'shop.playerOnline': 'ผู้เล่นออนไลน์',
        'shop.playerOffline': 'ผู้เล่นออฟไลน์',
        'shop.enterUsername': 'กรอกชื่อตัวละคร',
        'shop.targetUser': 'ซื้อให้ผู้เล่นอื่น (ไม่บังคับ)',
        'shop.gift': 'ส่งของขวัญ',
        'shop.checking': 'กำลังตรวจสอบ...',

        // Topup
        'topup.title': 'เติมเงิน',
        'topup.subtitle': 'เลือกแพ็คเกจที่คุณต้องการเพื่อสนับสนุนเซิร์ฟเวอร์',
        'topup.noPackages': 'ยังไม่มีแพ็คเกจในขณะนี้',
        'topup.buy': 'ซื้อทันที',
        'topup.confirm': 'ยืนยันการชำระเงิน',
        'topup.package': 'แพ็คเกจ',
        'topup.price': 'ราคา',
        'topup.method.qr': 'สแกน QR / พร้อมเพย์',
        'topup.method.truemoney': 'ซองของขวัญ TrueMoney',
        'topup.scanQR': 'สแกน QR Code นี้ด้วยแอปธนาคารของคุณ',
        'topup.promptPayIdNotSet': 'ยังไม่ได้ตั้งค่าพร้อมเพย์',
        'topup.promptPayLabel': 'เบอร์พร้อมเพย์',
        'topup.uploadSlip': 'อัปโหลดสลิปการโอนเงิน',
        'topup.angpaoLabel': 'ลิงก์ซองของขวัญ',
        'topup.angpaoHint': 'สร้างซองของขวัญจำนวน {amount} บาท (แบ่งเท่ากัน 1 คน)',
        'topup.accountLabel': 'บัญชีที่รับ',
        'topup.submitting': 'กำลังตรวจสอบ...',
        'topup.success': 'เติมเงินสำเร็จ! ได้รับพอยท์เรียบร้อยแล้ว',
        'topup.pending': 'ส่งข้อมูลการเติมเงินแล้ว โปรดรอแอดมินตรวจสอบ',
        // Dynamic Topup
        'topup.enterAmount': 'ระบุจำนวนเงิน (บาท)',
        'topup.calculatorTitle': 'คำนวณพอยท์',
        'topup.multiplierRate': 'เรทคูณ',
        'topup.receivePoints': 'คุณจะได้รับ',
        'topup.minAmount': 'ขั้นต่ำ 1 บาท',
        'topup.inputPlaceholder': 'กรอกจำนวนเงิน...',
        'topup.invalidAmount': 'กรุณาระบุจำนวนเงินที่ถูกต้อง',
        'admin.packageManage': 'จัดการแพ็คเกจพอยท์',
        'admin.packageCreate': 'สร้างแพ็คเกจใหม่',
        'admin.productManage': 'จัดการสินค้า',
        'admin.productCreate': 'ลงสินค้าใหม่',
        // Settings
        'admin.generalSettings': 'ตั้งค่าทั่วไป',
        'admin.siteTitle': 'ชื่อเว็บไซต์',
        'admin.settings.heroTitle': 'หัวข้อ Hero',
        'admin.settings.heroDescription': 'รายละเอียด Hero',
        'admin.settings.buttonText': 'ข้อความปุ่ม',
        'admin.settings.buttonAction': 'การทำงานของปุ่ม',
        'admin.siteLogo': 'โลโก้เว็บไซต์',
        'admin.siteBackground': 'พื้นหลังเว็บไซต์',
        'admin.siteFavicon': 'ไอคอนเว็บไซต์ (Favicon)',
        'admin.socialImage': 'รูปภาพแชร์โซเชียล',
        'admin.paymentSettings': 'ตั้งค่าการชำระเงิน',
        'admin.enableQrRequest': 'เปิดรับชำระผ่าน QR',
        'admin.enableTrueMoney': 'เปิดรับซองของขวัญ TrueMoney',
        'admin.promptPayNumber': 'เบอร์พร้อมเพย์',
        'admin.trueMoneyNumber': 'เบอร์ TrueMoney Wallet',
        'admin.slipVerification': 'ตรวจสอบสลิป',
        'admin.slipCheckMode': 'โหมดตรวจสลิป',
        'admin.manual': 'ตรวจสอบเอง (Admin กดอนุมัติ)',
        'admin.auto': 'อัตโนมัติ (Slip2Go)',
        'admin.slip2goApiKey': 'Slip2Go API Key',
        'admin.save': 'บันทึกการตั้งค่า',
        'admin.upload': 'อัปโหลด',
        // Topup Config
        'admin.settings.topupConfig': 'ตั้งค่าระบบเติมเงิน',
        'admin.settings.topupSystem': 'ระบบเติมเงิน',
        'admin.settings.topupMultiplier': 'ตัวคูณพอยท์ (Multiplier)',
        'admin.settings.topupSystemPackage': 'ระบบแพ็คเกจ (แนะนำ)',
        'admin.settings.topupSystemDynamic': 'ระบบกำหนดเอง (1:1 ตามเรทคูณ)',
        'admin.settings.topupDynamicHint': 'ผู้ใช้กรอกจำนวนเงิน และระบบคำนวณพอยท์ให้ตามตัวคูณ',
        'admin.settings.topupPackageHint': 'ผู้ใช้เลือกซื้อแพ็คเกจราคาตายตัว',
        'admin.settings.multiplierHint': 'เช่น ตัวคูณ 1.5, เติม 100 บาท ได้ 150 พอยท์',

        // Profile
        'profile.title': 'โปรไฟล์',
        'profile.points': 'พอยท์คงเหลือ',
        'profile.history': 'ประวัติการซื้อ',
        'profile.topupHistory': 'ประวัติการเติมเงิน',
        'profile.changeName': 'เปลี่ยนชื่อ',
        'profile.save': 'บันทึก',
        'profile.cancel': 'ยกเลิก',
        'profile.date': 'วันที่',
        'profile.item': 'รายการ',
        'profile.amount': 'จำนวน',
        'profile.status': 'สถานะ',
        'profile.noHistory': 'ไม่มีประวัติ',
        'profile.quickActions': 'เมนูด่วน',
        'profile.unknownPackage': 'ไม่พบแพ็คเกจ',
        'profile.emailNote': 'ไม่สามารถเปลี่ยนอีเมลได้',

        // Status
        'status.completed': 'สำเร็จ',
        'status.approved': 'อนุมัติแล้ว',
        'status.pending': 'รอดำเนินการ',
        'status.rejected': 'ปฏิเสธ',
        'status.failed': 'ล้มเหลว',

        // Support
        'support.title': 'ศูนย์ช่วยเหลือ',
        'support.submitTicket': 'ส่งคำร้อง',
        'support.yourTickets': 'คำร้องของคุณ',
        'support.subject': 'หัวข้อ',
        'support.message': 'ข้อความ',
        'support.category': 'หมวดหมู่ (ไม่บังคับ)',
        'support.selectCategory': 'เลือกหมวดหมู่...',
        'support.attachImage': 'แนบรูปภาพ (ไม่บังคับ)',
        'support.submit': 'ส่งคำร้อง',
        'support.submitting': 'กำลังส่ง...',
        'support.noTickets': 'ยังไม่มีคำร้อง',
        'support.noTicketsDesc': 'ส่งคำร้องแรกของคุณเพื่อเริ่มต้น',
        'support.pleaseLogin': 'กรุณาเข้าสู่ระบบ',
        'support.loginRequired': 'คุณต้องเข้าสู่ระบบเพื่อเข้าถึงการสนับสนุน',
        'support.goToLogin': 'ไปที่หน้าเข้าสู่ระบบ',
        'support.adminReply': 'การตอบกลับจากแอดมิน:',
        'support.clickToChange': 'คลิกเพื่อเปลี่ยนรูปภาพ',
        'support.clickToUpload': 'คลิกเพื่ออัพโหลดรูปภาพ',
        'support.imageHint': 'PNG, JPG, GIF ขนาดไม่เกิน 5MB',
        'admin.panel': 'แผงควบคุมแอดมิน',
        'admin.dashboard': 'ภาพรวมระบบ',
        'admin.info': 'ตั้งค่าเว็บไซต์',
        'admin.playerManagement': 'ข้อมูลผู้เล่น',
        'admin.serverStatus': 'สถานะเซิร์ฟเวอร์',
        'admin.console': 'คอนโซลเซิร์ฟเวอร์',
        'admin.wiki': 'จัดการวิกิ',
        'admin.supportTickets': 'รายการแจ้งปัญหา',
        'admin.pointPackages': 'จัดการแพ็คเกจ',
        'admin.storeProducts': 'จัดการสินค้า',
        'admin.userBalances': 'จัดการสมาชิก',
        'admin.transactions': 'ตรวจสอบการเติมเงิน',
        'admin.logout': 'ออกจากระบบ',
        'admin.logoutConfirmTitle': 'ออกจากระบบ',
        'admin.logoutConfirmDesc': 'คุณแน่ใจหรือไม่ที่จะออกจากระบบ?',

        // Admin Login
        'admin.login.title': 'แผงควบคุมแอดมิน',
        'admin.login.subtitle': 'กรอกรหัสผ่านเพื่อดำเนินการต่อ',
        'admin.login.password': 'รหัสผ่าน',
        'admin.login.placeholder': 'กรอกรหัสผ่านแอดมิน',
        'admin.login.loggingIn': 'กำลังเข้าสู่ระบบ...',
        'admin.login.submit': 'เข้าสู่ระบบ',
        'admin.login.backToHome': 'กลับสู่หน้าหลัก',
        'admin.login.invalidPassword': 'รหัสผ่านไม่ถูกต้อง',
        'admin.login.connectionError': 'เกิดข้อผิดพลาดในการเชื่อมต่อ โปรดลองอีกครั้ง',

        // Admin Pages
        'admin.products.title': 'จัดการสินค้า',
        'admin.products.add': 'เพิ่มสินค้า',
        'admin.products.name': 'ชื่อสินค้า',
        'admin.products.price': 'ราคา',
        'admin.products.image': 'รูปภาพ',
        'admin.products.command': 'คำสั่ง',
        'admin.products.description': 'รายละเอียด',
        'admin.products.category': 'หมวดหมู่',
        'admin.products.actions': 'จัดการ',
        'admin.products.edit': 'แก้ไข',
        'admin.products.delete': 'ลบ',
        'admin.products.confirmDelete': 'ยืนยันการลบสินค้า?',

        'admin.packages.title': 'จัดการแพ็คเกจ',
        'admin.packages.add': 'เพิ่มแพ็คเกจ',
        'admin.packages.points': 'พอยท์ที่จะได้รับ',
        'admin.packages.confirmDelete': 'ยืนยันการลบแพ็คเกจ?',
        'admin.packages.namePlaceholder': 'เช่น แพ็คเกจเริ่มต้น',
        'admin.packages.descPlaceholder': 'รายละเอียดแพ็คเกจ...',

        'admin.users.title': 'จัดการผู้ใช้',
        'admin.users.role': 'บทบาท',
        'admin.users.editPoints': 'แก้ไขพอยท์',
        'admin.users.save': 'บันทึก',
        'admin.users.banned': 'ถูกแบน',
        'admin.users.unban': 'ปลดแบน',
        'admin.users.ban': 'แบน',
        'admin.users.password': 'เปลี่ยนรหัสผ่าน',
        'admin.users.confirmDelete': 'ยืนยันการลบผู้ใช้?',
        'admin.users.passwordUpdated': 'เปลี่ยนรหัสผ่านสำเร็จ',
        'admin.users.changePassword': 'เปลี่ยนรหัสผ่าน',
        'admin.users.newPassword': 'รหัสผ่านใหม่',
        'admin.users.newPasswordPlaceholder': 'กรอกรหัสผ่านใหม่',
        'admin.users.total': 'ผู้ใช้ทั้งหมด',
        'admin.users.active': 'ผู้ใช้ที่ใช้งานอยู่',
        'admin.users.growth': 'การเติบโตของผู้ใช้',
        'admin.users.search': 'ค้นหาผู้ใช้...',
        'admin.users.noUsersFound': 'ไม่พบผู้ใช้',
        'admin.users.noUsers': 'ยังไม่มีผู้ใช้',


        'admin.wiki.title': 'จัดการวิกิ',
        'admin.wiki.add': 'เพิ่มบทความ',
        'admin.wiki.confirmDelete': 'ยืนยันการลบบทความ?',
        'admin.wiki.edit': 'แก้ไขบทความ',
        'admin.wiki.new': 'สร้างบทความใหม่',
        'admin.wiki.editDesc': 'แก้ไขรายละเอียดบทความของคุณ',
        'admin.wiki.newDesc': 'เขียนบทความใหม่สำหรับวิกิ',
        'admin.wiki.form.title': 'หัวข้อ',
        'admin.wiki.form.titlePlaceholder': 'กรอกหัวข้อบทความ',
        'admin.wiki.form.author': 'ผู้เขียน',
        'admin.wiki.form.authorPlaceholder': 'ชื่อผู้เขียน',
        'admin.wiki.form.coverImage': 'รูปปก',
        'admin.wiki.form.noImage': 'ไม่มีรูปภาพ',
        'admin.wiki.form.changeImage': 'เปลี่ยนรูปภาพ',
        'admin.wiki.form.uploadImage': 'อัพโหลดรูปภาพ',
        'admin.wiki.form.content': 'เนื้อหา',
        'admin.wiki.form.contentPlaceholder': 'เขียนเนื้อหาบทความที่นี่...',
        'admin.wiki.update': 'อัพเดทบทความ',
        'admin.wiki.publish': 'เผยแพร่บทความ',
        'admin.wiki.saveFailed': 'บันทึกบทความล้มเหลว',
        'admin.wiki.saveError': 'เกิดข้อผิดพลาดในการบันทึก',

        // Admin Settings
        'admin.settings.title': 'ตั้งค่าระบบ',
        'admin.settings.smtp': 'ตั้งค่า SMTP (อีเมล)',
        'admin.settings.smtpHost': 'SMTP Host',
        'admin.settings.smtpPort': 'SMTP Port',
        'admin.settings.smtpEmail': 'SMTP Email',
        'admin.settings.smtpPassword': 'SMTP Password',
        'admin.settings.smtpSecure': 'Secure (SSL/TLS)',
        'admin.settings.save': 'บันทึกการตั้งค่า',
        'admin.settings.saved': 'บันทึกการตั้งค่าเรียบร้อยแล้ว',
        'admin.settings.emailProvider': 'ผู้ให้บริการอีเมล',
        'admin.settings.provider.smtp': 'Custom SMTP',
        'admin.settings.provider.gmail': 'Gmail (ใช้ App Password)',
        'admin.settings.gmailHint': 'สำหรับ Gmail, กรุณาใช้ "App Password" แทนรหัสผ่านปกติของคุณ',
        'admin.settings.subtitle': 'จัดการเนื้อหาหน้าแรก ธีม และการตั้งค่าอื่นๆ',
        'admin.settings.resetDefaults': 'รีเซ็ตค่าเริ่มต้น',
        'admin.settings.homeContent': 'เนื้อหาหน้าแรก',
        'admin.server.title': 'ตั้งค่าเซิร์ฟเวอร์',
        'admin.server.status': 'สถานะเซิร์ฟเวอร์',
        'admin.server.ip': 'ที่อยู่ IP เซิร์ฟเวอร์',
        'admin.server.ipPlaceholder': 'เช่น play.example.com',
        'admin.server.pinging': 'กำลังตรวจสอบ...',
        'admin.server.checkStatus': 'ตรวจสอบสถานะ',
        'admin.server.rcon': 'ตั้งค่า RCON',
        'admin.server.authmeEnabled': 'เปิดใช้งานการเชื่อมต่อ AuthMe',
        'admin.server.authmeDesc': 'สมัครสมาชิกในเซิร์ฟเวอร์ Minecraft อัตโนมัติเมื่อสมัครสมาชิกบนเว็บไซต์',
        'admin.server.host': 'โฮสต์ RCON',
        'admin.server.port': 'พอร์ต RCON',
        'admin.server.rconPassword': 'รหัสผ่าน RCON',
        'admin.server.consoleName': 'ชื่อคอนโซล',
        'admin.server.saveConnection': 'บันทึกการเชื่อมต่อ',
        'admin.server.onlinePlayers': 'ผู้เล่นออนไลน์',
        'admin.server.showingPlayers': 'แสดง {length} จาก {online} คน',
        'admin.server.playerListHidden': 'รายชื่อผู้เล่นถูกซ่อน',
        'admin.server.hiddenDesc': 'มีผู้เล่นออนไลน์ {online} คน แต่เซิร์ฟเวอร์ไม่ได้ส่งตัวอย่างรายชื่อผู้เล่นมา',
        'admin.settings.serverIp': 'IP เซิร์ฟเวอร์',
        'admin.settings.mobileSupport': 'รองรับมือถือ (Bedrock)',
        'admin.settings.serverPort': 'พอร์ต',
        'admin.settings.sectionTitles': 'หัวข้อส่วนต่างๆ',
        'admin.settings.latestArticlesTitle': 'หัวข้อบทความล่าสุด',
        'admin.settings.whyChooseUsTitle': 'หัวข้อทำไมต้องเลือกเรา',
        'admin.settings.featureCards': 'การ์ดคุณสมบัติ',
        'admin.settings.addNewCard': 'เพิ่มการ์ดใหม่',
        'admin.settings.cardTitle': 'หัวข้อการ์ด',
        'admin.settings.cardColor': 'สีการ์ด',
        'admin.settings.cardDescription': 'รายละเอียดการ์ด',
        'admin.settings.changeImage': 'เปลี่ยนรูปภาพ',
        'admin.settings.uploadImage': 'อัพโหลดรูปภาพ',
        'admin.settings.addCard': 'เพิ่มการ์ด',
        'admin.settings.noCards': 'ยังไม่มีการ์ด',
        'admin.settings.themeSettings': 'ตั้งค่าธีม',
        'admin.settings.primaryColor': 'สีหลัก',
        'admin.settings.applyTheme': 'ใช้ธีม',
        'admin.settings.socialMedia': 'โซเชียลมีเดีย',
        'admin.settings.platform': 'แพลตฟอร์ม',
        'admin.settings.url': 'URL',
        'admin.settings.addSocial': 'เพิ่มโซเชียล',
        'admin.settings.noSocials': 'ยังไม่มีโซเชียลมีเดีย',
        'admin.settings.mediaAssets': 'ไฟล์สื่อ',
        'admin.settings.saveFailed': 'บันทึกการตั้งค่าล้มเหลว',
        'admin.settings.logoUploaded': 'อัพโหลดโลโก้แล้ว',
        'admin.settings.uploadFailed': 'อัพโหลดล้มเหลว',
        'admin.settings.bgUploaded': 'อัพโหลดพื้นหลังแล้ว',
        'admin.settings.faviconUploaded': 'อัพโหลด Favicon แล้ว',
        'admin.settings.qrUploaded': 'อัพโหลด QR Code แล้ว',
        'admin.settings.titleSaved': 'บันทึกชื่อเว็บไซต์แล้ว',
        'admin.settings.confirmReset': 'คุณแน่ใจหรือไม่ว่าต้องการรีเซ็ตเป็นค่าเริ่มต้น?',
        'admin.settings.cardCreated': 'สร้างการ์ดสำเร็จ',
        'admin.settings.createFailed': 'สร้างการ์ดล้มเหลว',
        'admin.settings.confirmDeleteCard': 'คุณแน่ใจหรือไม่ว่าต้องการลบการ์ดนี้?',
        'admin.settings.deleteFailed': 'ลบรายการล้มเหลว',
        'admin.settings.socialAdded': 'เพิ่มโซเชียลมีเดียแล้ว',
        'admin.settings.addFailed': 'เพิ่มโซเชียลมีเดียล้มเหลว',
        'admin.settings.confirmDeleteSocial': 'คุณแน่ใจหรือไม่ว่าต้องการลบโซเชียลมีเดียนี้?',
        'admin.settings.websiteLogo': 'โลโก้เว็บไซต์',
        'admin.settings.noLogo': 'ยังไม่ได้ตั้งค่าโลโก้',
        'admin.settings.chooseFile': 'เลือกไฟล์',
        'admin.settings.heroBackground': 'พื้นหลัง Hero',
        'admin.settings.noImage': 'ไม่มีรูปภาพ',
        'admin.settings.paymentQr': 'QR Code การชำระเงิน',
        'admin.settings.meetTheTeam': 'แนะนำทีมงาน',
        'admin.settings.teamTitle': 'หัวข้อทีมงาน',
        'admin.settings.teamSubtitle': 'รายละเอียดทีมงาน',
        'admin.settings.addMember': 'เพิ่มสมาชิก',
        'admin.settings.memberName': 'ชื่อ',
        'admin.settings.memberRole': 'บทบาท',
        'admin.settings.memberDesc': 'คำอธิบาย',
        'admin.settings.memberImage': 'รูปตัวละคร (URL)',
        'admin.settings.memberAvatar': 'รูปอวตาร (URL)',
        'admin.settings.memberOrder': 'ลำดับ',
        'admin.settings.confirmDeleteMember': 'คุณแน่ใจหรือไม่ว่าต้องการลบสมาชิกนี้?',
        'admin.settings.noQr': 'ไม่มี QR Code',
        'admin.settings.websiteFavicon': 'Favicon เว็บไซต์',
        'admin.settings.noFavicon': 'ไม่มี Favicon',
        'admin.settings.faviconHint': 'ขนาดที่แนะนำ 32x32 หรือ 64x64 px',
        'admin.settings.websiteTitle': 'ชื่อเว็บไซต์',
        'admin.settings.titleHint': 'จะแสดงในแท็บเบราว์เซอร์และแถบนำทาง',
        'admin.settings.socialSection': 'ส่วนโซเชียล (ด้านล่าง)',
        'admin.settings.socialTitle': 'หัวข้อโซเชียล',
        'admin.settings.socialDescription': 'รายละเอียดโซเชียล',
        'admin.settings.socialButtonText': 'ข้อความปุ่ม',
        'admin.settings.socialButtonLink': 'ลิงก์ปุ่ม',

        // Payment Settings
        'admin.settings.paymentSettings': 'ตั้งค่าการชำระเงิน',
        'admin.settings.slipCheckMode': 'โหมดตรวจสอบสลิป',
        'admin.settings.slipCheckMode.manual': 'ตรวจสอบเอง (Manual)',
        'admin.settings.slipCheckMode.auto': 'อัตโนมัติ (Slip2Go)',
        'admin.settings.slip2goApiKey': 'Slip2Go API Key',
        'admin.settings.slip2goApiKeyHint': 'คีย์ API สำหรับการตรวจสอบสลิปอัตโนมัติ',
        'admin.settings.socialImage': 'รูปภาพโซเชียล',
        'admin.settings.socialImageUploaded': 'อัพโหลดรูปภาพโซเชียลแล้ว',
        'admin.settings.seasonalSettings': 'ตั้งค่าเทศกาล',
        'admin.settings.seasonalEvent': 'เทศกาล/เหตุการณ์',
        'admin.settings.seasonal.none': 'ไม่มี',
        'admin.settings.seasonal.christmas': 'คริสต์มาส (หิมะตก)',
        'admin.settings.seasonal.mourning': 'ไว้อาลัย (โบว์ดำ)',
        'admin.settings.seasonal.newyear': 'ปีใหม่ (พลุ/Confetti)',
        'admin.settings.seasonal.halloween': 'ฮาโลวีน (ค้างคาว)',
        'admin.settings.seasonal.valentine': 'วาเลนไทน์ (หัวใจ)',

        // Auth
        'auth.forgotPassword': 'ลืมรหัสผ่าน?',
        'auth.resetPassword': 'รีเซ็ตรหัสผ่าน',
        'auth.sendResetLink': 'ส่งลิงก์รีเซ็ต',
        'auth.newPassword': 'รหัสผ่านใหม่',
        'auth.confirmNewPassword': 'ยืนยันรหัสผ่านใหม่',
        'auth.backToLogin': 'กลับไปหน้าเข้าสู่ระบบ',
        'auth.emailSent': 'ส่งอีเมลรีเซ็ตรหัสผ่านแล้ว',
        'auth.passwordsDoNotMatch': 'รหัสผ่านไม่ตรงกัน',
        'auth.resetSuccess': 'รีเซ็ตรหัสผ่านสำเร็จ',
        'auth.enterEmail': 'กรุณากรอกอีเมลของคุณ',

        // Home
        'home.heroTitle': 'สัมผัสประสบการณ์ Minecraft ที่ดีที่สุด',
        'home.heroDescription': 'เข้าร่วมเซิร์ฟเวอร์ของเราที่มีโหมดเกมที่ไม่เหมือนใคร ไอเท็มพิเศษ และชุมชนที่เป็นมิตร เริ่มต้นการผจญภัยของคุณวันนี้!',
        'home.browseShop': 'เลือกซื้อสินค้า',
        'home.copyIp': 'คัดลอก IP',
        'home.serverOnline': 'เซิร์ฟเวอร์ออนไลน์',
        'home.latestArticles': 'บทความล่าสุด',
        'home.whyChooseUs': 'ทำไมต้องเลือกเรา?',
        'home.features.community.title': 'ชุมชนที่ใช้งานอยู่',
        'home.features.community.desc': 'เข้าร่วมผู้เล่นนับพันในชุมชนที่เป็นมิตรและกระตือรือร้นของเรา',
        'home.features.performance.title': 'ประสิทธิภาพสูง',
        'home.features.performance.desc': 'ประสบการณ์ที่ลื่นไหลด้วยโครงสร้างพื้นฐานเซิร์ฟเวอร์ที่ปรับให้เหมาะสมของเรา',
        'home.features.events.title': 'กิจกรรมประจำ',
        'home.features.events.desc': 'เข้าร่วมกิจกรรมรายวันและรายสัปดาห์พร้อมของรางวัลสุดพิเศษ',
        'home.features.support.title': 'สนับสนุน 24/7',
        'home.features.support.desc': 'ทีมงานของเราพร้อมช่วยเหลือคุณเสมอ',

        // Home Products
        'home.products.title': 'สินค้าแนะนำ',
        'home.products.viewAll': 'ดูสินค้าทั้งหมด',
        'home.products.noProducts': 'ยังไม่มีสินค้าแนะนำ',

        // Top Donors & Rank
        'home.topDonors.title': 'ผู้สนับสนุนสูงสุด',
        'rank.title': 'จัดอันดับผู้สนับสนุน',
        'rank.allTime': 'ตลอดกาล',
        'rank.monthly': 'ประจำเดือน',
        'rank.col.rank': 'อันดับ',
        'rank.col.name': 'ชื่อผู้เล่น',
        'rank.col.amount': 'ยอดบริจาคสะสม',
        'rank.noData': 'ไม่มีข้อมูลการบริจาค',

        // Admin Transactions
        'admin.transactions.title': 'ตรวจสอบสลิป',
        'admin.transactions.date': 'วันที่',
        'admin.transactions.user': 'ผู้ใช้',
        'admin.transactions.package': 'แพ็คเกจ',
        'admin.transactions.amount': 'จำนวนเงิน',
        'admin.transactions.slip': 'สลิป',
        'admin.transactions.status': 'สถานะ',
        'admin.transactions.viewSlip': 'ดูสลิป',
        'admin.transactions.approve': 'อนุมัติ',
        'admin.transactions.reject': 'ปฏิเสธ',
        'admin.transactions.confirmApprove': 'คุณแน่ใจหรือไม่ที่จะอนุมัติรายการนี้?',
        'admin.transactions.confirmReject': 'คุณแน่ใจหรือไม่ที่จะปฏิเสธรายการนี้?',
        'admin.transactions.status.pending': 'รอดำเนินการ',
        'admin.transactions.status.approved': 'อนุมัติแล้ว',
        'admin.transactions.status.rejected': 'ปฏิเสธแล้ว',
        'admin.transactions.status.all': 'ทั้งหมด',
        'admin.transactions.updateTitle': 'อัพเดทรายการ',
        'admin.transactions.noTransactions': 'ไม่พบรายการ',



        // Auth (Missing)
        'auth.invalidCredentials': 'ข้อมูลเข้าสู่ระบบไม่ถูกต้อง',
        'auth.login': 'เข้าสู่ระบบ',
        'admin.restricted': 'พื้นที่จำกัด',
        'auth.username': 'ชื่อผู้ใช้',
        'auth.password': 'รหัสผ่าน',
        'auth.logout': 'ออกจากระบบ',
        'auth.email': 'อีเมล',

        // Admin Tickets (More Missing)
        'admin.tickets.confirmDelete': 'คุณแน่ใจหรือไม่ที่จะลบคำร้องนี้?',
        'admin.tickets.status.unread': 'ยังไม่อ่าน',
        'admin.tickets.status.read': 'อ่านแล้ว',
        'admin.tickets.status.replied': 'ตอบกลับแล้ว',
        'admin.tickets.status.resolved': 'แก้ไขแล้ว',
        'admin.tickets.title': 'คำร้องสนับสนุน',
        'admin.tickets.hideTags': 'ซ่อนป้ายกำกับ',
        'admin.tickets.manageTags': 'จัดการป้ายกำกับ',
        'admin.tickets.searchPlaceholder': 'ค้นหาตามหัวข้อ, ข้อความ, ผู้ใช้ หรือป้ายกำกับ...',
        'adminTickets.all': 'ทั้งหมด',
        'admin.tickets.listTitle': 'รายการคำร้อง',
        'adminTickets.noTickets': 'ไม่พบคำร้อง',
        'admin.tickets.detailsTitle': 'รายละเอียดคำร้อง',
        'admin.tickets.userInfo': 'ข้อมูลผู้ใช้',
        'admin.tickets.subject': 'หัวข้อ',
        'admin.tickets.category': 'หมวดหมู่',
        'admin.tickets.message': 'ข้อความ',
        'admin.tickets.attachment': 'ไฟล์แนบ',
        'admin.tickets.yourReply': 'การตอบกลับของคุณ',
        'admin.tickets.sendReply': 'ส่งคำตอบ',
        'adminTickets.typeReply': 'พิมพ์คำตอบของคุณ...',
        'admin.tickets.sending': 'กำลังส่ง...',
        'admin.tickets.changeStatus': 'เปลี่ยนสถานะ',
        'admin.tickets.markRead': 'ทำเครื่องหมายว่าอ่านแล้ว',
        'admin.tickets.markResolved': 'ทำเครื่องหมายว่าแก้ไขแล้ว',
        'admin.tickets.delete': 'ลบคำร้อง',
        'admin.tickets.selectTicket': 'เลือกคำร้องเพื่อดูรายละเอียด',

        // Admin Products (Additions)
        'admin.products.namePlaceholder': 'เช่น ดาบเพชร',
        'admin.products.descPlaceholder': 'รายละเอียดสินค้า...',
        'admin.products.commandHint': 'ใช้ [player] แทนชื่อผู้เล่น',
        'admin.products.tag': 'ข้อความป้ายกำกับ',
        'admin.products.tagColor': 'สีป้ายกำกับ',
        'admin.products.optional': '(ไม่บังคับ)',
        'admin.products.allowGift': 'อนุญาตให้ส่งของขวัญ',

        // Admin Packages (Additions)
        'admin.packages.qrCode': 'QR Code แพ็คเกจ',
        'admin.packages.qrHint': 'ใช้แทน QR Code หลักสำหรับแพ็คเกจนี้',

        // Admin Payment Settings
        'admin.settings.payment': 'ตั้งค่าการชำระเงิน',
        'admin.settings.payment.qrTitle': 'พร้อมเพย์ QR',
        'admin.settings.payment.qrDesc': 'สร้าง QR Code พร้อมเพย์อัตโนมัติจากเบอร์ที่ระบุ',
        'admin.settings.payment.promptPayNumber': 'เบอร์พร้อมเพย์ / เลขบัตรประชาชน',
        'admin.settings.payment.promptPayHint': 'เบอร์นี้จะถูกนำไปสร้าง QR Code สำหรับยอดเงินแต่ละรายการ',
        'admin.settings.payment.tmTitle': 'ทรูมันนี่ วอลเล็ท (ซองของขวัญ)',
        'admin.settings.payment.tmDesc': 'รับชำระเงินผ่านลิงก์ซองของขวัญ',
        'admin.settings.payment.tmNumber': 'เบอร์โทรศัพท์ผู้รับ (สำหรับอ้างอิง)',
        'admin.settings.payment.tmHint': 'ใช้สำหรับแสดงให้ผู้เล่นทราบเท่านั้น การรับเงินจะทำผ่านลิงก์',


        // Admin Tickets (Additions)
        'adminTickets.manageCategories': 'จัดการหมวดหมู่',
        'adminTickets.createCategory': 'สร้างหมวดหมู่ใหม่',
        'adminTickets.categoryName': 'ชื่อหมวดหมู่...',
        'adminTickets.existingCategories': 'หมวดหมู่ที่มีอยู่',
        'adminTickets.noCategories': 'ยังไม่มีหมวดหมู่ สร้างใหม่ด้านบน!',
        'adminTickets.confirmDeleteTag': 'คุณแน่ใจหรือไม่ที่จะลบป้ายกำกับนี้?',

        // Admin Wiki (Additions)
        'admin.wiki.subtitle': 'สร้างและจัดการบทความชุมชน',
        'admin.wiki.noArticles': 'ไม่พบบทความ สร้างใหม่เพื่อเริ่มต้น!',

        // Common
        'common.optional': '(ไม่บังคับ)',
        'common.loading': 'กำลังโหลด...',
        'common.save': 'บันทึก',
        'common.cancel': 'ยกเลิก',
        'common.delete': 'ลบ',
        'common.edit': 'แก้ไข',
        'common.create': 'สร้าง',
        'common.upload': 'อัพโหลด',
        'common.close': 'ปิด',
        'common.success': 'สำเร็จ',
        'common.error': 'ข้อผิดพลาด',
        'common.warning': 'คำเตือน',
        'common.info': 'ข้อมูล',
        'common.saving': 'กำลังบันทึก...',
        'common.saveChanges': 'บันทึกการเปลี่ยนแปลง',
        'common.adding': 'กำลังเพิ่ม...',
        'common.copied': 'คัดลอกแล้ว!',
        'common.readMore': 'อ่านเพิ่มเติม',
        'common.article': 'บทความ',
        'common.search': 'ค้นหา...',
        'common.check': 'ตรวจสอบ',
        'common.download': 'ดาวน์โหลดตัวเกม',
        'common.copyIp': 'คัดลอก IP',

        // Social Section
        'social.title': 'มาเป็นส่วนหนึ่งกับเรา!',
        'social.description': 'ที่ Origin Realms เราเชื่อว่าการสื่อสารคือกุญแจสำคัญสู่ชุมชนที่ยอดเยี่ยม เข้าร่วม Discord ของเราเพื่อพูดคุยกับเพื่อนใหม่และทีมงาน!',
        'social.joinDiscord': 'เข้าร่วม Discord ของเรา',

        // Footer
        'footer.about': 'เกี่ยวกับเรา',
        'footer.quickLinks': 'เมนูลัด',
        'footer.followUs': 'ติดตามเรา',
        'footer.rights': 'สงวนลิขสิทธิ์',
        'footer.description': 'เข้าร่วมชุมชน Minecraft ที่ดีที่สุดและเริ่มต้นการผจญภัยของคุณวันนี้!',
        'footer.credit': 'Website by Cumulus Dev',

        // Legal Pages
        'common.lastUpdated': 'อัปเดตล่าสุด',
        'terms.title': 'ข้อกำหนดการให้บริการ',
        'terms.acceptance': 'การยอมรับข้อตกลง',
        'terms.usage': 'การใช้งาน',
        'terms.purchases': 'การซื้อสินค้า',
        'terms.termination': 'การยุติการให้บริการ',
        'terms.changes': 'การเปลี่ยนแปลง',
        'privacy.title': 'นโยบายความเป็นส่วนตัว',
        'privacy.collection': 'การเก็บรวบรวมข้อมูล',
        'privacy.usage': 'การใช้ข้อมูล',
        'privacy.cookies': 'คุกกี้',
        'privacy.security': 'ความปลอดภัย',
        'privacy.contact': 'ติดต่อเรา',

        // 404 Page
        'notFound.title': 'ไม่พบหน้าที่คุณต้องการ',
        'notFound.description': 'ดูเหมือนว่าคุณจะหลงทางในโลกของ Minecraft! หน้าที่คุณกำลังมองหาอาจถูกลบ เปลี่ยนชื่อ หรือไม่สามารถใช้งานได้ในขณะนี้',
        'notFound.backHome': 'กลับสู่หน้าหลัก',
        'notFound.contactSupport': 'ติดต่อฝ่ายสนับสนุน',

        // Error Page
        'error.title': 'เกิดข้อผิดพลาดบางอย่าง',
        'error.description': 'ขออภัย เกิดปัญหาที่ไม่คาดคิดขึ้น เรากำลังพยายามแก้ไขปัญหานี้โดยเร็วที่สุด',
        'error.retry': 'ลองใหม่อีกครั้ง',
        'error.backHome': 'กลับสู่หน้าหลัก',

        // Wiki Page
        'wiki.title': 'วิกิชุมชน',
        'wiki.subtitle': 'สำรวจคู่มือ บทช่วยสอน และการอัปเดตจากชุมชน',
        'wiki.noArticles': 'ไม่พบบทความ',
        'wiki.checkBack': 'กลับมาตรวจสอบใหม่ภายหลัง!',
    },
    en: {
        // Navbar
        'nav.home': 'Home',
        'nav.store': 'Store',
        'nav.wiki': 'Wiki',
        'nav.support': 'Support',
        'nav.login': 'Login',
        'nav.register': 'Register',
        'nav.logout': 'Logout',
        'nav.admin': 'Admin',
        'nav.profile': 'Profile',
        'nav.logoutConfirmTitle': 'Logout',
        'nav.logoutConfirmDesc': 'Are you sure you want to logout?',
        'nav.balance': 'Balance',



        // Login
        'login.title': 'Sign In',
        'login.subtitle': 'Welcome back',
        'login.email': 'Email',
        'login.username': 'Username',
        'login.password': 'Password',
        'login.rememberMe': 'Remember me',
        'login.forgotPassword': 'Forgot password?',
        'login.submit': 'Sign In',
        'login.noAccount': "Don't have an account?",
        'login.signUp': 'Sign up',

        // Register
        'register.title': 'Sign Up',
        'register.subtitle': 'Create your account',
        'register.name': 'Username',
        'register.email': 'Email',
        'register.password': 'Password',
        'register.passwordHint': 'Must be at least 8 characters long',
        'register.submit': 'Sign Up',
        'register.hasAccount': 'Already have an account?',
        'register.signIn': 'Sign in',

        // Shop
        'shop.title': 'Store',
        'shop.subtitle': 'Purchase items for your character',
        'shop.search': 'Search items...',
        'shop.all': 'All',
        'shop.buy': 'Buy',
        'shop.price': 'Price',
        'shop.points': 'Points',
        'shop.outOfStock': 'Out of Stock',
        'shop.confirmBuy': 'Confirm Purchase',
        'shop.confirmBuyDesc': 'Are you sure you want to buy this item?',
        'shop.success': 'Purchase Successful',
        'shop.error': 'Purchase Failed',
        'shop.insufficientPoints': 'Insufficient Points',
        'shop.insufficientPointsDesc': 'You do not have enough points to buy this item. Please top up.',
        'shop.topup': 'Topup',
        'shop.checkOnline': 'Check Online Status',
        'shop.playerOnline': 'Player Online',
        'shop.playerOffline': 'Player Offline',
        'shop.enterUsername': 'Enter Username',
        'shop.targetUser': 'Buy for another player (Optional)',
        'shop.gift': 'Gift',
        'shop.checking': 'Checking...',
        'topup.title': 'Top Up',
        'topup.subtitle': 'Choose your preferred package to support the server',
        'topup.noPackages': 'No packages available at the moment.',
        'topup.buy': 'Buy Now',
        'topup.confirm': 'Confirm Payment',
        'topup.package': 'Package',
        'topup.price': 'Price',
        'topup.method.qr': 'Scan QR / PromptPay',
        'topup.method.truemoney': 'TrueMoney Angpao',
        'topup.scanQR': 'Scan this QR Code with your banking app',
        'topup.promptPayIdNotSet': 'PromptPay ID not configured',
        'topup.promptPayLabel': 'PromptPay ID',
        'topup.uploadSlip': 'Upload Payment Slip',
        'topup.angpaoLabel': 'Truemoney Angpao Link',
        'topup.angpaoHint': 'Create an Angpao for {amount} Baht (Divide equally for 1 person)',
        'topup.accountLabel': 'Account',
        'topup.submitting': 'Verifying...',
        'topup.success': 'Top-up successful! Points have been added to your account.',
        'topup.pending': 'Top-up submitted! Please wait for admin approval.',
        'topup.noQR': 'QR Code not configured',
        // Dynamic Topup
        'topup.enterAmount': 'Enter Amount (THB)',
        'topup.calculatorTitle': 'Point Calculator',
        'topup.multiplierRate': 'Rate',
        'topup.receivePoints': 'You will receive',
        'topup.minAmount': 'Minimum amount is 1 THB',
        'topup.inputPlaceholder': 'Enter amount...',
        'topup.invalidAmount': 'Please enter a valid amount',
        'admin.packageManage': 'Manage Point Packages',
        'admin.packageCreate': 'Create New Package',
        'admin.products': 'Products',
        'admin.productManage': 'Manage Products',
        'admin.productCreate': 'Create New Product',
        // Settings
        'admin.generalSettings': 'General Settings',
        'admin.siteTitle': 'Site Title',
        'admin.settings.heroTitle': 'Hero Title',
        'admin.settings.heroDescription': 'Hero Description',
        'admin.settings.buttonText': 'Button Text',
        'admin.settings.buttonAction': 'Button Action',
        'admin.siteLogo': 'Site Logo',
        'admin.siteBackground': 'Site Background',
        'admin.siteFavicon': 'Site Favicon',
        'admin.socialImage': 'Social Share Image',
        'admin.paymentSettings': 'Payment Settings',
        'admin.enableQrRequest': 'Enable QR Payment',
        'admin.enableTrueMoney': 'Enable TrueMoney Angpao',
        'admin.promptPayNumber': 'PromptPay Number',
        'admin.trueMoneyNumber': 'TrueMoney Number',
        'admin.slipVerification': 'Slip Verification',
        'admin.slipCheckMode': 'Slip Check Mode',
        'admin.manual': 'Manual (Admin checks slips)',
        'admin.auto': 'Automatic (Slip2Go)',
        'admin.slip2goApiKey': 'Slip2Go API Key',
        'admin.save': 'Save Settings',
        'admin.upload': 'Upload',
        // Topup Config
        'admin.settings.topupConfig': 'Topup Configuration',
        'admin.settings.topupSystem': 'Topup System',
        'admin.settings.topupMultiplier': 'Point Multiplier',
        'admin.settings.topupSystemPackage': 'Package System (Recommended)',
        'admin.settings.topupSystemDynamic': 'Dynamic System (1:1 with Multiplier)',
        'admin.settings.topupDynamicHint': 'Users input an amount, and points are calculated based on the multiplier.',
        'admin.settings.topupPackageHint': 'Users buy predefined packages with fixed points.',
        'admin.settings.multiplierHint': 'e.g., If multiplier is 1.5, paying 100 THB gives 150 Points.',

        // Topup

        // Profile
        'profile.title': 'Profile',
        'profile.points': 'Points Balance',
        'profile.history': 'Purchase History',
        'profile.topupHistory': 'Topup History',
        'profile.changeName': 'Change Name',
        'profile.save': 'Save',
        'profile.cancel': 'Cancel',
        'profile.date': 'Date',
        'profile.item': 'Item',
        'profile.amount': 'Amount',
        'profile.status': 'Status',
        'profile.noHistory': 'No history found',
        'profile.quickActions': 'Quick Actions',
        'profile.unknownPackage': 'Unknown Package',
        'profile.emailNote': 'Email cannot be changed.',

        // Status
        'status.completed': 'Completed',
        'status.approved': 'Approved',
        'status.pending': 'Pending',
        'status.rejected': 'Rejected',
        'status.failed': 'Failed',

        // Support
        'support.title': 'Support Center',
        'support.submitTicket': 'Submit a Ticket',
        'support.yourTickets': 'Your Tickets',
        'support.subject': 'Subject',
        'support.message': 'Message',
        'support.category': 'Category (Optional)',
        'support.selectCategory': 'Select a category...',
        'support.attachImage': 'Attach Image (Optional)',
        'support.submit': 'Submit Ticket',
        'support.submitting': 'Submitting...',
        'support.noTickets': 'No tickets yet',
        'support.noTicketsDesc': 'Submit your first ticket to get started',
        'support.pleaseLogin': 'Please Login',
        'support.loginRequired': 'You need to be logged in to access support',
        'support.goToLogin': 'Go to Login',
        'support.adminReply': 'Admin Reply:',
        'support.clickToChange': 'Click to change image',
        'support.clickToUpload': 'Click to upload image',
        'support.imageHint': 'PNG, JPG, GIF up to 5MB',
        'support.sessionError': 'Invalid user session. Please logout and login again.',
        'support.submitSuccess': 'Ticket submitted successfully!',
        'support.submitError': 'Failed to submit ticket',
        'support.submitErrorGeneric': 'An error occurred while submitting the ticket. Please try again.',

        // Admin Sidebar
        'admin.dashboard': 'Dashboard',
        'admin.info': 'Info (Web Settings)',
        'admin.playerManagement': 'Player Management',
        'admin.serverStatus': 'Server Status',
        'admin.console': 'Console (RCON)',
        'admin.wiki': 'Wiki / Blog',
        'admin.supportTickets': 'Support Tickets',
        'admin.panel': 'Admin Panel',
        'admin.pointPackages': 'Point Packages',
        'admin.storeProducts': 'Store Products',
        'admin.userBalances': 'User Balances',
        'admin.transactions': 'Verify Slips',
        'admin.logout': 'Logout',
        'admin.logoutConfirmTitle': 'Logout',
        'admin.logoutConfirmDesc': 'Are you sure you want to logout?',

        // Admin Login
        'admin.login.title': 'Admin Panel',
        'admin.login.subtitle': 'Enter password to continue',
        'admin.login.password': 'Password',
        'admin.login.placeholder': 'Enter admin password',
        'admin.login.loggingIn': 'Logging in...',
        'admin.login.submit': 'Login',
        'admin.login.backToHome': 'Back to Home',
        'admin.login.invalidPassword': 'Invalid password',
        'admin.login.connectionError': 'Connection error. Please try again.',

        // Admin Pages
        'admin.products.title': 'Manage Products',
        'admin.products.add': 'Add Product',
        'admin.products.name': 'Product Name',
        'admin.products.price': 'Price',
        'admin.products.image': 'Image',
        'admin.products.command': 'Command',
        'admin.products.description': 'Description',
        'admin.products.category': 'Category',
        'admin.products.allowGift': 'Allow Gifting',
        'admin.products.actions': 'Actions',
        'admin.products.edit': 'Edit',
        'admin.products.delete': 'Delete',
        'admin.products.confirmDelete': 'Are you sure you want to delete this product?',
        'admin.products.namePlaceholder': 'e.g. Diamond Sword',
        'admin.products.descPlaceholder': 'Product description...',
        'admin.products.commandHint': 'Use [player] as placeholder',
        'admin.products.tag': 'Tag Text',
        'admin.products.tagColor': 'Tag Color',
        'admin.products.optional': '(Optional)',

        'admin.packages.title': 'Manage Packages',
        'admin.packages.add': 'Add Package',
        'admin.packages.points': 'Points Received',
        'admin.packages.confirmDelete': 'Are you sure you want to delete this package?',
        'admin.packages.namePlaceholder': 'e.g. Starter Pack',
        'admin.packages.descPlaceholder': 'Package details...',
        'admin.packages.qrCode': 'Package QR Code',
        'admin.packages.qrHint': 'Overrides main QR Code for this package',

        // Admin Payment Settings
        'admin.settings.payment': 'Payment Settings',
        'admin.settings.payment.qrTitle': 'PromptPay QR',
        'admin.settings.payment.qrDesc': 'Automatically generate PromptPay QR from the ID',
        'admin.settings.payment.promptPayNumber': 'PromptPay Number / ID',
        'admin.settings.payment.promptPayHint': 'This ID will be used to generate dynamic QR codes for each transaction.',
        'admin.settings.payment.tmTitle': 'TrueMoney Wallet (Angpao)',
        'admin.settings.payment.tmDesc': 'Accept payments via Angpao links',
        'admin.settings.payment.tmNumber': 'Receiver Phone Number (Reference)',
        'admin.settings.payment.tmHint': 'Used for display purposes only. Payments are processed via links.',

        'admin.users.title': 'Manage Users',
        'admin.users.role': 'Role',
        'admin.users.editPoints': 'Edit Points',
        'admin.users.save': 'Save',
        'admin.users.banned': 'Banned',
        'admin.users.unban': 'Unban',
        'admin.users.ban': 'Ban',
        'admin.users.password': 'Password',
        'admin.users.confirmDelete': 'Are you sure you want to delete this user?',
        'admin.users.passwordUpdated': 'Password updated successfully',
        'admin.users.changePassword': 'Change Password',
        'admin.users.newPassword': 'New Password',
        'admin.users.newPasswordPlaceholder': 'Enter new password',
        'admin.users.total': 'Total Users',
        'admin.users.active': 'Active Users',
        'admin.users.growth': 'User Growth',
        'admin.users.search': 'Search users...',
        'admin.users.noUsersFound': 'No users found',
        'admin.users.noUsers': 'No users yet',



        'admin.wiki.title': 'Manage Wiki',
        'admin.wiki.add': 'Add Article',
        'admin.wiki.confirmDelete': 'Are you sure you want to delete this article?',
        'admin.wiki.edit': 'Edit Article',
        'admin.wiki.new': 'New Article',
        'admin.wiki.editDesc': 'Edit your article details',
        'admin.wiki.newDesc': 'Write a new article for the wiki',
        'admin.wiki.form.title': 'Title',
        'admin.wiki.form.titlePlaceholder': 'Enter article title',
        'admin.wiki.form.author': 'Author',
        'admin.wiki.form.authorPlaceholder': 'Author name',
        'admin.wiki.form.coverImage': 'Cover Image',
        'admin.wiki.form.noImage': 'No image',
        'admin.wiki.form.changeImage': 'Change Image',
        'admin.wiki.form.uploadImage': 'Upload Image',
        'admin.wiki.form.content': 'Content',
        'admin.wiki.form.contentPlaceholder': 'Write your article content here...',
        'admin.wiki.update': 'Update Article',
        'admin.wiki.publish': 'Publish Article',
        'admin.wiki.saveFailed': 'Failed to save article',
        'admin.wiki.saveError': 'Error saving article',

        // Admin Settings
        'admin.settings.title': 'Website Settings',
        'admin.settings.smtp': 'SMTP Settings (Email)',
        'admin.settings.smtpHost': 'SMTP Host',
        'admin.settings.smtpPort': 'SMTP Port',
        'admin.settings.smtpEmail': 'SMTP Email',
        'admin.settings.smtpPassword': 'SMTP Password',
        'admin.settings.smtpSecure': 'Secure (SSL/TLS)',
        'admin.settings.emailProvider': 'Email Provider',
        'admin.settings.provider.smtp': 'Custom SMTP',
        'admin.settings.provider.gmail': 'Gmail (Use App Password)',
        'admin.settings.gmailHint': 'For Gmail, please use an "App Password" instead of your regular password.',
        'admin.settings.subtitle': 'Manage home content, theme, and other settings',
        'admin.settings.resetDefaults': 'Reset Defaults',
        'admin.settings.homeContent': 'Home Page Content',
        'admin.server.title': 'Server Settings',
        'admin.server.showingPlayers': 'Showing {length} of {online} players',
        'admin.server.playerListHidden': 'Player List Hidden',
        'admin.server.hiddenDesc': 'There are {online} players online, but the server is not sending the player list sample.',
        'admin.settings.serverIp': 'Server IP',
        'admin.settings.mobileSupport': 'Mobile Support (Bedrock)',
        'admin.settings.serverPort': 'Port',
        'admin.settings.sectionTitles': 'Section Titles',
        'admin.settings.latestArticlesTitle': 'Latest Articles Title',
        'admin.settings.whyChooseUsTitle': 'Why Choose Us Title',
        'admin.settings.featureCards': 'Feature Cards',
        'admin.settings.addNewCard': 'Add New Card',
        'admin.settings.cardTitle': 'Card Title',
        'admin.settings.cardColor': 'Card Color',
        'admin.settings.cardDescription': 'Card Description',
        'admin.settings.changeImage': 'Change Image',
        'admin.settings.uploadImage': 'Upload Image',
        'admin.settings.addCard': 'Add Card',
        'admin.settings.noCards': 'No cards yet',
        'admin.settings.themeSettings': 'Theme Settings',
        'admin.settings.primaryColor': 'Primary Color',
        'admin.settings.applyTheme': 'Apply Theme',
        'admin.settings.socialMedia': 'Social Media',
        'admin.settings.platform': 'Platform',
        'admin.settings.url': 'URL',
        'admin.settings.addSocial': 'Add Social',
        'admin.settings.noSocials': 'No social media yet',
        'admin.settings.mediaAssets': 'Media Assets',
        'admin.settings.saved': 'Settings saved',
        'admin.settings.saveFailed': 'Failed to save settings',
        'admin.settings.logoUploaded': 'Logo uploaded',
        'admin.settings.uploadFailed': 'Upload failed',
        'admin.settings.bgUploaded': 'Background uploaded',
        'admin.settings.faviconUploaded': 'Favicon uploaded',
        'admin.settings.qrUploaded': 'QR Code uploaded',
        'admin.settings.titleSaved': 'Site title saved',
        'admin.settings.heroBackground': 'Hero Background',
        'admin.settings.noImage': 'No image',
        'admin.settings.paymentQr': 'Payment QR Code',
        'admin.settings.meetTheTeam': 'Meet The Team',
        'admin.settings.teamTitle': 'Team Title',
        'admin.settings.teamSubtitle': 'Team Subtitle',
        'admin.settings.addMember': 'Add Member',
        'admin.settings.memberName': 'Name',
        'admin.settings.memberRole': 'Role',
        'admin.settings.memberDesc': 'Description',
        'admin.settings.memberImage': 'Character Image (URL)',
        'admin.settings.memberAvatar': 'Avatar Image (URL)',
        'admin.settings.memberOrder': 'Order',
        'admin.settings.confirmDeleteMember': 'Are you sure you want to delete this member?',
        'admin.settings.noQr': 'No QR Code',
        'admin.settings.websiteFavicon': 'Website Favicon',
        'admin.settings.noFavicon': 'No favicon',
        'admin.settings.faviconHint': 'Recommended size 32x32 or 64x64 px',
        'admin.settings.websiteTitle': 'Website Title',
        'admin.settings.titleHint': 'Will be displayed in browser tab and navbar',
        'admin.settings.seasonalSettings': 'Seasonal Settings',
        'admin.settings.seasonal.christmas': 'Christmas (Snow)',
        'admin.settings.seasonal.mourning': 'Mourning (Black Ribbon)',
        'admin.settings.seasonal.newyear': 'New Year (Confetti)',
        'admin.settings.seasonal.halloween': 'Halloween (Bats)',
        'admin.settings.seasonal.valentine': 'Valentine (Hearts)',
        'admin.settings.socialSection': 'Social Section (Bottom)',
        'admin.settings.socialTitle': 'Social Title',
        'admin.settings.socialDescription': 'Social Description',
        'admin.settings.socialButtonText': 'Button Text',
        'admin.settings.socialButtonLink': 'Button Link',

        // Payment Settings
        'admin.settings.paymentSettings': 'Payment Settings',
        'admin.settings.slipCheckMode': 'Slip Check Mode',
        'admin.settings.slipCheckMode.manual': 'Manual Check',
        'admin.settings.slipCheckMode.auto': 'Automatic (Slip2Go)',
        'admin.settings.slip2goApiKey': 'Slip2Go API Key',
        'admin.settings.slip2goApiKeyHint': 'API Key for automatic slip verification',
        'admin.settings.socialImage': 'Social Image',
        'admin.settings.socialImageUploaded': 'Social image uploaded',
        'admin.settings.chooseFile': 'Choose File',

        // Admin Tickets
        'adminTickets.title': 'Support Tickets',
        'adminTickets.manageTags': 'Manage',
        'adminTickets.hideTags': 'Hide',
        'adminTickets.tags': 'Tags',
        'adminTickets.search': 'Search by subject, message, user, or tag...',
        'adminTickets.all': 'All',
        'adminTickets.unread': 'Unread',
        'adminTickets.read': 'Read',
        'adminTickets.replied': 'Replied',
        'adminTickets.resolved': 'Resolved',
        'adminTickets.tickets': 'Tickets',
        'adminTickets.noTickets': 'No tickets found',
        'adminTickets.selectTicket': 'Select a ticket to view details',
        'adminTickets.ticketDetails': 'Ticket Details',
        'adminTickets.userInfo': 'User Information',
        'adminTickets.subject': 'Subject',
        'adminTickets.category': 'Category',
        'adminTickets.message': 'Message',
        'adminTickets.attachment': 'Attachment',
        'adminTickets.yourReply': 'Your Reply',
        'adminTickets.sendReply': 'Send Reply',
        'adminTickets.typeReply': 'Type your reply...',
        'adminTickets.sending': 'Sending...',
        'adminTickets.changeStatus': 'Change Status',
        'adminTickets.markAsRead': 'Mark as Read',
        'adminTickets.markResolved': 'Mark Resolved',
        'adminTickets.deleteTicket': 'Delete Ticket',

        // Home
        'home.heroTitle': 'Experience the Ultimate Minecraft Gameplay',
        'home.heroDescription': 'Join our immersive server featuring unique game modes, custom items, and a friendly community. Start your adventure today!',
        'home.browseShop': 'Browse Shop',
        'home.copyIp': 'Copy IP',
        'home.serverOnline': 'Server Online',
        'home.latestArticles': 'Latest Articles',
        'home.whyChooseUs': 'Why Choose Us?',
        'home.features.community.title': 'Active Community',
        'home.features.community.desc': 'Join thousands of players in our friendly and active community.',
        'home.features.performance.title': 'High Performance',
        'home.features.performance.desc': 'Lag-free experience with our optimized server infrastructure.',
        'home.features.events.title': 'Regular Events',
        'home.features.events.desc': 'Participate in daily and weekly events with amazing rewards.',
        'home.features.support.title': '24/7 Support',
        'home.features.support.desc': 'Our dedicated staff team is always ready to help you.',


        // Admin Tickets (Additions)
        'adminTickets.manageCategories': 'Manage Categories',
        'adminTickets.createCategory': 'Create New Category',
        'adminTickets.categoryName': 'Category name...',
        'adminTickets.existingCategories': 'Existing Categories',
        'adminTickets.noCategories': 'No categories yet. Create one above!',
        'adminTickets.confirmDeleteTag': 'Are you sure you want to delete this tag?',

        // Admin Tickets (More)
        'admin.tickets.title': 'Support Tickets',
        'admin.tickets.searchPlaceholder': 'Search by subject, message, user, or tag...',
        'admin.tickets.manageTags': 'Manage Tags',
        'admin.tickets.hideTags': 'Hide Tags',
        'admin.tickets.listTitle': 'Tickets',
        'admin.tickets.detailsTitle': 'Ticket Details',
        'admin.tickets.userInfo': 'User Information',
        'admin.tickets.subject': 'Subject',
        'admin.tickets.category': 'Category',
        'admin.tickets.message': 'Message',
        'admin.tickets.attachment': 'Attachment',
        'admin.tickets.yourReply': 'Your Reply',
        'admin.tickets.sendReply': 'Send Reply',
        'admin.tickets.sending': 'Sending...',
        'admin.tickets.changeStatus': 'Change Status',
        'admin.tickets.markRead': 'Mark as Read',
        'admin.tickets.markResolved': 'Mark Resolved',
        'admin.tickets.delete': 'Delete Ticket',
        'admin.tickets.selectTicket': 'Select a ticket to view details',
        'admin.tickets.status.unread': 'Unread',
        'admin.tickets.status.read': 'Read',
        'admin.tickets.status.replied': 'Replied',
        'admin.tickets.status.resolved': 'Resolved',
        'admin.tickets.confirmDelete': 'Are you sure you want to delete this ticket?',

        // Admin Transactions
        'admin.transactions.title': 'Transaction Verification',
        'admin.transactions.date': 'Date',
        'admin.transactions.user': 'User',
        'admin.transactions.package': 'Package',
        'admin.transactions.amount': 'Amount',
        'admin.transactions.slip': 'Slip',
        'admin.transactions.status': 'Status',
        'admin.transactions.viewSlip': 'View Slip',
        'admin.transactions.approve': 'Approve',
        'admin.transactions.reject': 'Reject',
        'admin.transactions.confirmApprove': 'Are you sure you want to approve this transaction?',
        'admin.transactions.confirmReject': 'Are you sure you want to reject this transaction?',
        'admin.transactions.status.pending': 'Pending',
        'admin.transactions.status.approved': 'Approved',
        'admin.transactions.status.rejected': 'Rejected',
        'admin.transactions.status.all': 'All',
        'admin.transactions.updateTitle': 'Update Transaction',

        // Admin Wiki (Additions)
        'admin.wiki.subtitle': 'Create and manage community articles',
        'admin.wiki.noArticles': 'No articles found. Create one to get started!',

        // Home Products
        'home.products.title': 'Featured Items',
        'home.products.viewAll': 'View All Products',
        'home.products.noProducts': 'No featured items yet',

        // Top Donors & Rank
        'home.topDonors.title': 'Top Donors',
        'rank.title': 'Donation Ranking',
        'rank.allTime': 'All Time',
        'rank.monthly': 'Monthly',
        'rank.col.rank': 'Rank',
        'rank.col.name': 'Player Name',
        'rank.col.amount': 'Total Donated',
        'rank.noData': 'No donation data available',

        // Auth (Missing)
        'auth.invalidCredentials': 'Invalid credentials',
        'auth.login': 'Login',
        'admin.restricted': 'Restricted Area',
        'auth.username': 'Username',
        'auth.password': 'Password',
        'auth.logout': 'Logout',
        'auth.email': 'Email',

        // Common
        'common.optional': '(Optional)',
        'common.loading': 'Loading...',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.create': 'Create',
        'common.upload': 'Upload',
        'common.close': 'Close',
        'common.success': 'Success',
        'common.error': 'Error',
        'common.warning': 'Warning',
        'common.info': 'Info',
        'common.saving': 'Saving...',
        'common.saveChanges': 'Save Changes',
        'common.adding': 'Adding...',
        'common.copied': 'Copied!',
        'common.readMore': 'Read More',
        'common.article': 'Article',
        'common.search': 'Search...',
        'common.check': 'Check',
        'common.download': 'Download Game',
        'common.copyIp': 'Copy IP',

        // Social Section
        'social.title': 'Let\'s Be Social!',
        'social.description': 'Here on Origin Realms we think communication is the key to an amazing community. Because of that, we heavily value our Discord and the way it allows us to connect with our favourite people ever - you! Come join us, and let\'s create our origin - together!',
        'social.joinDiscord': 'JOIN OUR DISCORD',

        // Footer
        'footer.about': 'About Us',
        'footer.quickLinks': 'Quick Links',
        'footer.followUs': 'Follow Us',
        'footer.rights': 'All Rights Reserved.',
        'footer.description': 'Join the best Minecraft community and start your adventure today!',
        'footer.credit': 'Website by Cumulus Dev',

        // Legal Pages
        'common.lastUpdated': 'Last Updated',
        'terms.title': 'Terms of Service',
        'terms.acceptance': 'Acceptance of Agreement',
        'terms.usage': 'Usage',
        'terms.purchases': 'Purchases',
        'terms.termination': 'Termination',
        'terms.changes': 'Changes',
        'privacy.title': 'Privacy Policy',
        'privacy.collection': 'Information Collection',
        'privacy.usage': 'Information Usage',
        'privacy.cookies': 'Cookies',
        'privacy.security': 'Security',
        'privacy.contact': 'Contact Us',

        // 404 Page
        'notFound.title': 'Page Not Found',
        'notFound.description': 'Looks like you got lost in the Minecraft world! The page you are looking for might have been removed, renamed, or is temporarily unavailable.',
        'notFound.backHome': 'Back to Home',
        'notFound.contactSupport': 'Contact Support',

        // Error Page
        'error.title': 'Something went wrong!',
        'error.description': 'Sorry, an unexpected error has occurred. We are working to fix this issue as soon as possible.',
        'error.retry': 'Try Again',
        'error.backHome': 'Back to Home',

        // Wiki Page
        'wiki.title': 'Community Wiki',
        'wiki.subtitle': 'Explore guides, tutorials, and updates from the community.',
        'wiki.noArticles': 'No articles found.',
        'wiki.checkBack': 'Check back later for updates!',



    },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>('th');

    useEffect(() => {
        // Load language from localStorage
        try {
            const saved = localStorage.getItem('language') as Language;
            if (saved && (saved === 'th' || saved === 'en')) {
                setLanguageState(saved);
            }
        } catch (e) {
            console.warn('Failed to load language from localStorage', e);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        try {
            localStorage.setItem('language', lang);
        } catch (e) {
            console.warn('Failed to save language to localStorage', e);
        }
    };

    const t = (key: string): string => {
        const lang = translations[language];
        return (lang as Record<string, string>)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
}
